# Generated by Django 4.0.1 on 2022-02-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
    ]
